### ISSUE TITLE
SOS 2.0 Test Suite sos:IRRequestInvalidresultValues test fails for SOAP

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#12]
The sos:IRRequestInvalidresultValues test fails for SOAP because the value of
the 'template' element is missing.
[Originally reported in the OGC CITE issue tracker: issue #752](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=752)  

_Opened: 2012-12-21 05:52:23 _

**Comment by rockygis** [comment]
The value of the 'template' element is from $InsertResultTemplateResponse//sos:InsertResultTemplateResponse/sos:acceptedTemplate. 
And maybe the response of InsertResultTemplate is empty or error, so that the template is missing.

There are some issues about InsertResult, so we temporarily hide the test.
