### ISSUE TITLE
 Structure of exception response is ExceptionReport/Exception

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sos20#15]
For exception reporting OGC 06-121 Section 8 describes and shows an <ExceptionReport><Exception> structure.  But the SOAP test in the SOS_ETS.XML CTL file uses the following XPath expression to check the exception: select="$exceptionReport//soap12:Detail/ows:Exception[1]"

**Comment by rockygis** [comment]
The structure of exception response is ExceptionReport/Exception.

This bug is Fixed and Updated.

The examples of SOS 2.0 on the web is incorrect.
http://schemas.opengis.net/sos/2.0/examples/SOAP/sosException_InvalidPropertyOfferingCombination_SOAP12Fault.xml
http://schemas.opengis.net/sos/2.0/examples/core/Exception_ResponseExceedsSizeLimit.xml
