### ISSUE TITLE
Enable REST API

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-sos20#26]

**Comment by keshavnangare** [comment]
@lgoltz 

We need to restructure the test as the ETS has two interactive forms to select the test and for selecting the URL's. The REST need non-interactive tests. Should we execute all the tests instead of selecting it?


Form 1:

![image](https://user-images.githubusercontent.com/14732650/51301010-bdc62d00-1a53-11e9-91c9-10e31e71ba7a.png)

Form 2:

![image](https://user-images.githubusercontent.com/14732650/51371792-2b8c5a80-1b21-11e9-8308-ae38d0b58b54.png)


In form2 we have to select URL for the test. Should we run all the test by default?

Following are URLs in the form2 in each dropdown:

http://sensorweb.demo.52north.org/52n-sos-webapp/service/kvp
http://sensorweb.demo.52north.org/52n-sos-webapp/service/exi
http://sensorweb.demo.52north.org/52n-sos-webapp/service/json
http://sensorweb.demo.52north.org/52n-sos-webapp/service/pox
http://sensorweb.demo.52north.org/52n-sos-webapp/service/soap

**Comment by dstenger** [comment]
Default values:
* `HTTP Get` and `Run all tests`

This restriction should be documented and a new issue must be created to refactor the test suite to make it more suitable for REST interface.

Especially, second form cannot be manipulated by REST interface.
